### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by LowkeyCoding** [jonasKjellerup/f-appen#1]
The navbar component should contain the fklub logo followed by a list of fklub services and a connection status display. The list of services should collapse on mobile devices into a burger menu. In addition to the services, there should be a link to the profile page or login popup. The connection status should be a colored element and a small status message. 

- [x] Logo
- [x] Connection status
- [x] Navigation links

**Comment by jonasKjellerup** [comment]
Closed in #17
